language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

  exclude:
      - php: 5.3
        env: SYMFONY_VERSION=dev-master
      - php: 5.4
        env: SYMFONY_VERSION=dev-master

sudo: false

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --no-update -v
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-dist --no-update -v
  - composer -vvv install --prefer-dist --no-dev
  - ls -a /home/travis/build/azine/* -R

script:
  - phpunit --coverage-clover=coverage.clover /home/travis/build/azine/AzineHybridAuthBundle/Tests/
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: travis@azine-it.ch
