<?php

namespace Azine\HybridAuthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HybridAuthSessionDataRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HybridAuthSessionDataRepository extends EntityRepository
{
}
